sudo: required
addons:
  apt:
    sources:
    - sourceline: 'deb http://ppa.launchpad.net/tboox/xmake/ubuntu yakkety main'
    - sourceline: 'ppa:boost-latest/ppa'
    - ubuntu-toolchain-r-test
    packages:
    - xmake
    - boost1.55
    - g++-6
before_install:
  - wget https://github.com/avplayer/avhttp/archive/v2.9.9.tar.gz
  - tar xvzf v2.9.9.tar.gz
  - cd avhttp-2.9.9
  - sudo cp -r include/* /usr/include
script:
  - xmake config --cc=gcc-6 --cxx=g++-6 --sh=sh
  - xmake
